apiVersion: v1
kind: Service
metadata:
  name: floridaservice
  labels:
    app: florida
    role: service
    tier: backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: florida
    role: test
    tier: backend
